"""Docket Generator — Produces the Tribunal Docket verdict report.

The Docket is the primary output artifact of the Governance Tribunal.
It documents the incident, investigation, patch, validation evidence,
and verdict in a structured, auditable format.
"""

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, Template


# Inline template as fallback if template file is not found
INLINE_TEMPLATE = """
====================================================================
TRIBUNAL DOCKET: CASE #{{ case_id }}
DEFENDANT: {{ defendant }}
CHARGES: {{ charges }}
DATE: {{ date }}
====================================================================

## 1. THE INCIDENT (What Failed)
{{ incident_details }}

## 2. THE MOTIVE (Root Cause Analysis)
{{ root_cause }}
Confidence Score: {{ confidence }}

## 3. THE INVESTIGATION TRAIL
- Suspect Commit: {{ suspect_commit }}
- Author: {{ suspect_author }}
- Commit Message: {{ suspect_message }}
- Files Analyzed: {{ files_changed }}

## 4. THE SENTENCE (The Patch)
{{ patch_description }}

## 5. DUAL-VALIDATION EVIDENCE
{% for check in validations %}
- [{{ check.status }}] {{ check.description }}
{% endfor %}

## 6. PAROLE CONDITIONS (Guardrails Added)
{% for condition in parole_conditions %}
- {{ condition }}
{% endfor %}

## 7. RISK ASSESSMENT
- Case Type: {{ case_type }}
- Severity: {{ severity }}
- Human Approval Required: {{ human_approval_required }}
- Residual Risks: {{ residual_risks }}

## 8. REMEDIATION ATTEMPTS
- Total Attempts: {{ attempt_count }}
- Final Status: {{ final_status }}

**VERDICT:** {{ verdict }}
====================================================================
Generated by The Governance Tribunal — Powered by IBM Bob 2.0
"""


class DocketGenerator:
    """Generates the Tribunal Docket from case data and investigation results."""

    def __init__(self, template_dir: str = "templates"):
        self.template_dir = Path(template_dir)
        self._template = self._load_template()

    def _load_template(self) -> Template:
        """Load Jinja2 template from file or use inline fallback."""
        template_file = self.template_dir / "docket_template.md"
        if template_file.exists():
            env = Environment(
                loader=FileSystemLoader(str(self.template_dir)),
                keep_trailing_newline=True,
            )
            return env.get_template("docket_template.md")
        return Template(INLINE_TEMPLATE)

    def generate(self, case: Any, result: dict[str, Any]) -> str:
        """Render the Tribunal Docket from case and result data."""
        # Build incident details
        incident_lines = self._build_incident_details(case)

        data = {
            "case_id": case.case_id,
            "defendant": ", ".join(
                case.evidence.get("changed_files", ["unknown file"])
            ),
            "charges": self._format_charges(case),
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "incident_details": "\n".join(incident_lines) or "No incidents detected.",
            "root_cause": result.get("root_cause", "Under investigation"),
            "confidence": case.confidence_score,
            "suspect_commit": result.get("suspect", {}).get("commit", "N/A")[:7],
            "suspect_author": result.get("suspect", {}).get("author", "N/A"),
            "suspect_message": result.get("suspect", {}).get("message", "N/A"),
            "files_changed": ", ".join(result.get("files_patched", ["N/A"])),
            "patch_description": result.get("patch_summary", "No patch generated."),
            "validations": result.get("validations", []),
            "parole_conditions": result.get("parole_conditions", []),
            "case_type": case.case_type.value if hasattr(case.case_type, 'value') else str(case.case_type),
            "severity": case.severity.value if hasattr(case.severity, 'value') else str(case.severity),
            "human_approval_required": (
                (case.severity.value == "high" if hasattr(case.severity, 'value') else True)
                or case.confidence_score < 0.75
            ),
            "residual_risks": result.get("residual_risks", "None identified."),
            "attempt_count": case.attempt_count,
            "final_status": case.status.value if hasattr(case.status, 'value') else str(case.status),
            "verdict": result.get("verdict", "PENDING"),
        }

        return self._template.render(data)

    def _build_incident_details(self, case: Any) -> list[str]:
        """Extract incident details from case evidence."""
        lines: list[str] = []

        # Test failures
        for failure in case.evidence.get("test_results", {}).get("failures", []):
            test_id = failure.get("test_id", "unknown")
            message = failure.get("message", "no details")
            lines.append(f"- Functional: {test_id} FAILED — {message}")

        # Secret findings
        secrets = case.evidence.get("secret_scan", {}).get("findings", {})
        for filepath, secret_list in secrets.items():
            for secret in secret_list:
                stype = secret.get("type", "Unknown")
                sline = secret.get("line_number", "?")
                lines.append(f"- Policy: {stype} detected in {filepath} (line {sline})")

        # PII findings
        for finding in case.evidence.get("pii_scan", {}).get("findings", []):
            ftype = finding.get("type", "PII")
            ffile = finding.get("file", "unknown")
            fline = finding.get("line", "?")
            lines.append(f"- Policy: {ftype} detected in {ffile} (line {fline})")

        return lines

    def _format_charges(self, case: Any) -> str:
        """Format the charges string from case evidence."""
        charges = []
        test_fails = case.evidence.get("test_results", {}).get("failed_count", 0)
        if test_fails > 0:
            charges.append(f"{test_fails}x Functional Regression")

        secret_count = sum(
            len(v) for v in
            case.evidence.get("secret_scan", {}).get("findings", {}).values()
        )
        if secret_count > 0:
            charges.append(f"{secret_count}x Secret Violation")

        pii_count = len(case.evidence.get("pii_scan", {}).get("findings", []))
        if pii_count > 0:
            charges.append(f"{pii_count}x Privacy Policy Violation")

        return ", ".join(charges) or "No charges filed"
