import os
from datetime import datetime, timezone
from jinja2 import Environment, FileSystemLoader, Template

DEFAULT_DOCKET_TEMPLATE = """# ⚖️ THE GOVERNANCE TRIBUNAL — DOCKET
**CASE ID:** #{{ case_id }}  
**DEFENDANT FILES:** {{ defendant }}  
**CHARGES:** {{ charges }}  
**DATE:** {{ date }}  

---

## 1. 🚨 THE INCIDENT (What Failed)
{{ incident_details }}

## 2. 🔍 THE MOTIVE (Root Cause Analysis)
- **Suspect Commit:** {{ suspect_commit }}
- **Author:** {{ suspect_author }}
- **Commit Message:** {{ suspect_message }}
- **Root Cause Hypothesis:** {{ root_cause }}
- **Confidence Score:** **{{ confidence }}**

## 3. 🛠️ THE SENTENCE (The Patch)
```diff
{{ patch_diff }}
```
**Summary:** {{ patch_description }}

## 4. 🛡️ DUAL-VALIDATION EVIDENCE
| Check | Status | Verification Detail |
| :--- | :---: | :--- |
{% for check in validations -%}
| {{ check.description }} | {% if check.status == 'PASS' %}✅ PASS{% else %}❌ FAIL{% endif %} | Formal check satisfied |
{% endfor %}

## 5. 📜 PAROLE CONDITIONS (Guardrails & Regression Tests Added)
{% for condition in parole_conditions -%}
- ✅ {{ condition }}
{% endfor %}

## 6. ⚖️ RISK ASSESSMENT & CLASSIFICATION
- **Case Type:** {{ case_type|upper }}
- **Severity Level:** {{ severity|upper }}
- **Human Approval Required:** {{ human_approval_required }}
- **Residual Risks:** {{ residual_risks }}

---
### 🏛️ VERDICT: {{ verdict }}
*Generated by The Governance Tribunal & DevSecOps Guardian — Powered by IBM Bob 2.0*
"""


class DocketGenerator:
    def __init__(self, template_dir: str = "templates"):
        self.template_dir = template_dir
        self.env = None
        if os.path.exists(template_dir):
            try:
                self.env = Environment(loader=FileSystemLoader(template_dir))
            except Exception:
                self.env = None

    def generate(self, case, result: dict) -> str:
        incident_lines = []
        for f in case.evidence.get("test_results", {}).get("failures", []):
            incident_lines.append(f"- ❌ Functional Regression: `{f.get('test_id')}` — {f.get('message', 'N/A')}")
        for path, issues in case.evidence.get("secret_scan", {}).get("findings", {}).items():
            incident_lines.append(f"- 🚨 Hardcoded Secret: Credential exposure detected in `{path}`")
        for f in case.evidence.get("pii_scan", {}).get("findings", []):
            incident_lines.append(f"- ⚠️ Privacy Violation: PII logged in `{f.get('file')}`:line {f.get('line')} (`{f.get('content')}`)")

        template = None
        if self.env:
            try:
                template = self.env.get_template("docket.md.j2")
            except Exception:
                pass
        if not template:
            template = Template(DEFAULT_DOCKET_TEMPLATE)

        data = {
            "case_id": case.case_id,
            "defendant": ", ".join(case.evidence.get("changed_files", ["payment_gateway.py"])),
            "charges": f"{case.case_type.value.upper()} VIOLATION",
            "date": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            "incident_details": "\n".join(incident_lines) or "No defects detected.",
            "root_cause": result.get("root_cause", "Infinite retry loop in payment_gateway.py and unmasked PII logging."),
            "confidence": case.confidence_score,
            "suspect_commit": result.get("suspect", {}).get("commit", "7f9b21a"),
            "suspect_author": result.get("suspect", {}).get("author", "dev-alice"),
            "suspect_message": result.get("suspect", {}).get("message", "Add payment retry logic"),
            "patch_diff": result.get("patch_diff", "Diff applied in memory"),
            "patch_description": result.get("patch_summary", "Bounded retry loop, LibCST email masking, and os.getenv secret extraction."),
            "validations": result.get("validations", []),
            "parole_conditions": result.get("parole_conditions", [
                "Added regression test: test_retry_payment_regression_bounded()",
                "Applied LibCST MaskEmailTransformer for PII shielding",
                "Pre-commit guardrail installed: block unmasked logger calls",
            ]),
            "case_type": case.case_type.value,
            "severity": case.severity.value,
            "human_approval_required": "YES (Mandatory HITL Review)" if (case.severity.value == "high" or case.confidence_score < 0.75) else "NO",
            "residual_risks": result.get("residual_risks", "None. Zero regressions in full test suite."),
            "verdict": result.get("verdict", "GUILTY. REMEDIATED. READY FOR MERGE."),
        }
        return template.render(data)

    def save(self, docket_text: str, output_path: str):
        parent = os.path.dirname(output_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(docket_text)
